models:
  kimi-k2.5:
    base_url: "https://api.moonshot.cn/v1"
    api_key: "sk-vSQIhNSP9DRrtpoNGZDmZFOJKSZJJ48EZILOxzuEkHkq1vPq"
    temperature: 1
    top_p: 0.95
  GLM-4.7-Flash:
    base_url: "https://open.bigmodel.cn/api/paas/v4"
    api_key: "da3969354d034ad5a7d5430c68011fc1.Gyf0KrWAIrBnjHxL"
    temperature: 1
    top_p: 0.95
  "Qwen/Qwen2.5-7B-Instruct":
    base_url: "https://api.siliconflow.cn/v1"
    api_key: "sk-jtehryojqfehlplhebndsxagwruvcfcqlwfmsqhdwlrymycp"
    temperature: 1
    top_p: 0.95
  "THUDM/GLM-Z1-9B-0414":
    base_url: "https://api.siliconflow.cn/v1"
    api_key: "sk-jtehryojqfehlplhebndsxagwruvcfcqlwfmsqhdwlrymycp"
    temperature: 1
    top_p: 0.95
  "Qwen/Qwen3-8B": #好用
    base_url: "https://api.siliconflow.cn/v1"
    api_key: "sk-jtehryojqfehlplhebndsxagwruvcfcqlwfmsqhdwlrymycp"
    temperature: 1
    top_p: 0.95
  "deepseek-ai/DeepSeek-OCR": #限免
    base_url: "https://api.siliconflow.cn/v1"
    api_key: "sk-jtehryojqfehlplhebndsxagwruvcfcqlwfmsqhdwlrymycp"
    temperature: 1
    top_p: 0.95